parameters:
  werkint_cache.metadata.annotationdriver.class:
    Werkint\Bundle\CacheBundle\Service\Metadata\AnnotationDriver
  werkint_cache.metadata.metadatafactory.class:
    Metadata\MetadataFactory

services:
  werkint_cache.metadata.annotationdriver:
    class: %werkint_cache.metadata.annotationdriver.class%
    arguments:
      - @annotation_reader
  werkint_cache.metadata.metadatafactory:
    class: %werkint_cache.metadata.metadatafactory.class%
    arguments:
      - @werkint_cache.metadata.annotationdriver
